version: '3.7'

services:
  redis:
    container_name: parser_redis
    hostname: parser_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - dgs

  db:
    image: postgres
    container_name: parser_db
    hostname: parser_db
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg_data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dgs

  app:
    container_name: parser_app
    hostname: parser_app
    build:
      context: .
      dockerfile: app/Dockerfile
    entrypoint: /app/entrypoint.sh
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    volumes:
      - ${LOG_PATH}:/app/logs
      - ./app:/app/
    networks:
      - dgs
    depends_on:
      - redis
      - db

  celery_worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: app/Dockerfile
    command: sh -c "poetry run celery -A src worker -l info --pool=solo"
    container_name: parser_celery_worker
    hostname: parser_celery_worker
    env_file:
      - .env.dev
    volumes:
      - ${LOG_PATH}:/app/logs
      - ./app:/app/
    depends_on:
      - redis
      - db
      - app
    networks:
      - dgs


  celery-beat:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: celery -A src beat -l info
    container_name: parser_celery_beat
    hostname: parser_celery_beat
    env_file:
      - ./app/.env.dev
    volumes:
      - ./app:/app/
    depends_on:
      - app
      - redis
      - db
      - celery_worker
    networks:
      - dgs



networks:
  dgs:
    driver: bridge
