# Generated by Django 4.0.3 on 2022-04-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('hyphen', models.CharField(default='-', max_length=1)),
                ('u', models.CharField(default='-', help_text='frank', max_length=5)),
                ('time', models.DateTimeField()),
                ('method', models.CharField(default='-', max_length=6)),
                ('url', models.CharField(default='-', max_length=500)),
                ('protocol', models.CharField(default='-', max_length=1)),
                ('code', models.CharField(max_length=3)),
                ('size', models.CharField(max_length=6)),
                ('referer', models.URLField()),
                ('agent', models.CharField(max_length=60)),
            ],
        ),
    ]
