# Generated by Django 4.0.3 on 2022-04-07 15:04

import aggregator.services.path_log_files
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(help_text='h', protocol='IPv4')),
                ('indent', models.CharField(default='-', help_text='l', max_length=1)),
                ('user', models.CharField(default='-', help_text='u, frank', max_length=5)),
                ('time', models.DateTimeField(help_text='t')),
                ('method', models.CharField(default='-', help_text='%r -> m', max_length=6)),
                ('url', models.CharField(default='-', help_text='%r -> U', max_length=500)),
                ('protocol', models.CharField(default='-', help_text='%r -> H', max_length=15)),
                ('status', models.CharField(help_text='>s', max_length=15)),
                ('size', models.CharField(help_text='b', max_length=15)),
                ('referrer', models.URLField(help_text='Referer')),
                ('agent', models.CharField(help_text='User-agent', max_length=600)),
                ('other', models.CharField(help_text='User-agent', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FilePathField(match='.*\\.log$', path=aggregator.services.path_log_files.logs_path)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(help_text='User-agent', max_length=600)),
            ],
        ),
    ]
