# Generated by Django 4.0.3 on 2022-04-07 19:21

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='file',
            field=models.FilePathField(match='.*\\.log$', path=pathlib.PurePosixPath('/app/logs')),
        ),
    ]
