# Generated by Django 4.0.3 on 2022-04-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_remove_log_u_log_userid_alter_log_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='protocol',
            field=models.CharField(default='-', help_text='%r -> H', max_length=10),
        ),
    ]
