# Generated by Django 4.0.3 on 2022-04-06 17:28

import aggregator.services.path_log_files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_logfile_testlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='file',
            field=models.FilePathField(match='.*\\.log$', path=aggregator.services.path_log_files.logs_path),
        ),
    ]
