# Generated by Django 4.0.3 on 2022-04-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_alter_logfile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='hyphen',
            new_name='indent',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='referer',
            new_name='referrer',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='userid',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='log',
            name='code',
        ),
        migrations.AddField(
            model_name='log',
            name='other',
            field=models.CharField(default=1, help_text='User-agent', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(default=1, help_text='>s', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='protocol',
            field=models.CharField(default='-', help_text='%r -> H', max_length=15),
        ),
        migrations.AlterField(
            model_name='log',
            name='size',
            field=models.CharField(help_text='b', max_length=15),
        ),
    ]
